-- ============================================================================
-- VANTA LABS — STOP THE PUBLIC KEY READING THE SHELF DEPTH
--
-- Finding RLS-07. APPLIED TO PRODUCTION 2026-08-28. Safe to re-run: revoking a
-- privilege that is not held is a no-op.
--
-- IT SAT IN THIS DIRECTORY UNAPPLIED, WHICH IS WORSE THAN SITTING ANYWHERE ELSE.
-- The header used to read "NOT APPLIED YET", while
-- products-hide-cost-columns-from-public.sql:126 and its product_doses sibling
-- had both been edited to say "WITHHELD SINCE 2026-08-28 (finding RLS-07)". So
-- two files asserted the hole was closed, a third said it was open, and the
-- directory those three live in is treated as the record of what ran. Anyone
-- auditing the repo would have concluded the columns were withheld.
--
-- They were not. Reproduced 2026-08-28 against production with the storefront's
-- OWN publishable key, before changing anything:
--
--   GET /rest/v1/products?select=slug,inventory_quantity,reserved_quantity,
--                                incoming_quantity,low_stock_threshold
--     -> 200  [{"slug":"igf-1-lr3","inventory_quantity":19,"reserved_quantity":0,
--               "incoming_quantity":0,"low_stock_threshold":5}, ...]
--
--   GET /rest/v1/product_doses?select=label,inventory_quantity,reserved_quantity,
--                                     incoming_quantity
--     -> 200  [{"label":"5mg","inventory_quantity":29, ...}, ...]
--
-- Controls run in the same breath, so the probe proves something: the cost
-- columns returned 42501, and label/price_cents/stock_status returned 200. The
-- key could read exactly what it should not and nothing more.
--
-- AFTER APPLYING, same key:
--   products.inventory_quantity   -> 42501
--   product_doses.reserved_quantity -> 42501
--   all four columns on both tables: has_column_privilege(anon) = false
--   KEPT: products.stock_status = true, product_doses.price_cents = true
--
--   www.vantalabsresearch.com / /products /products/bpc-157 /cart /checkout
--   /api/catalog/products -> 200 on all six; 36 products, 36 with doses, and a
--   dose still published as {"availableQuantity":10,"stockStatus":"In Stock"} —
--   the CLAMPED figure, which is the whole point of the finding.
--
-- Found by an adversarial review of the repository, not by a test.
-- phase11-bucket7.test.ts:387 asserts these revoke statements exist as TEXT in
-- this file; it cannot assert the file was ever run, which is why the suite was
-- green throughout. A repo test cannot close this class of gap — only a probe
-- against the real database can, and that is now recorded above.
--
-- WHAT IS WRONG. products-hide-cost-columns-from-public.sql revoked table-level
-- SELECT and re-granted a named column list. That list included the raw stock
-- quantities, on the stated ground that they are "already exposed by the public
-- catalogue API". They are not. src/lib/catalog.ts says the opposite, in as
-- many words:
--
--   // inventoryQuantity is deliberately ABSENT. These objects are handed to
--   // client components, so anything on them is readable in the page source;
--   // the shelf depth is the owner's information.
--
-- What the catalogue publishes is an AVAILABILITY figure, and it is clamped:
-- publishableAvailability() returns min(available, MAX_UNITS_PER_ORDER_LINE),
-- so a reader of the page source learns at most "ten or more". The PostgREST
-- grant handed that same anonymous key the uncapped count, plus
-- reserved_quantity (how fast the line is moving right now) and
-- incoming_quantity (when the restock lands) — neither of which the application
-- publishes in any form. The application capped the disclosure; the grant
-- undid the cap.
--
-- WHAT IS KEPT, AND WHY. stock_status is the derived badge the storefront is
-- built on, and track_inventory is a boolean that discloses no depth, so both
-- stay granted. batch_number, lab_name and testing_date stay too — the product
-- page renders them from the same server route, so they are public by design.
--
-- WHY THIS BREAKS NOTHING. No browser code reads either table. Ten files import
-- the browser client from @/lib/supabase, and the only table read between them
-- is `ambassadors` in lib/referral-client.ts — src/lib/client-key-table-access.test.ts
-- is the standing guard on that. Every catalogue read runs server-side under
-- service_role, which bypasses grants and RLS alike.
--
-- THE ONE THING TO WATCH. app/admin/products/page.tsx subscribes to
-- postgres_changes on `products` and `product_doses` from the browser client,
-- and Realtime evaluates the subscriber's own access. The supabase_realtime
-- publication contains no tables in this project (verified 2026-08-27 when
-- product-doses-hide-cost-columns-from-public.sql was applied), so that
-- subscription delivers nothing either way today. If the publication is ever
-- switched on, confirm the admin list still auto-refreshes — the blast radius
-- is contained either way, because the handler only calls loadProducts(),
-- which is a server route running under service_role.
-- ============================================================================

begin;

revoke select (inventory_quantity, reserved_quantity, incoming_quantity, low_stock_threshold)
  on public.products from anon, authenticated;

revoke select (inventory_quantity, reserved_quantity, incoming_quantity, low_stock_threshold)
  on public.product_doses from anon, authenticated;

commit;

-- ============================================================================
-- VERIFY (expect: rows for the first, 42501 for the second and third):
--
--   set role anon;
--   select slug, price_cents, stock_status from public.products limit 1;
--   select inventory_quantity from public.products limit 1;      -- must fail
--   select reserved_quantity from public.product_doses limit 1;  -- must fail
--   reset role;
--
-- And the storefront must be unchanged: /api/catalog/products still returns
-- every product with its doses and its clamped availability figure, because
-- that route runs under service_role.
--
-- ROLLBACK, if this ever needs undoing in a hurry:
--
--   grant select (inventory_quantity, reserved_quantity, incoming_quantity, low_stock_threshold)
--     on public.products to anon, authenticated;
--   grant select (inventory_quantity, reserved_quantity, incoming_quantity, low_stock_threshold)
--     on public.product_doses to anon, authenticated;
--
-- The two source migrations were edited in the same change to drop these four
-- names from their grant lists, so re-running either of them no longer restores
-- what this revokes.
-- ============================================================================
