import "server-only";

import { supabaseAdmin } from "@/lib/supabase-server";
import { normalizeCouponCode } from "@/lib/coupons";

export type AdminCoupon = {
  id: string;
  code: string;
  discountType: "percent" | "fixed";
  discountValue: number;
  startsAt: string | null;
  endsAt: string | null;
  maxRedemptions: number | null;
  redemptionsCount: number;
  active: boolean;
  createdAt: string;
  /** Auto-generated per-customer abandoned-cart recovery code (has an
   *  assigned_email). Shown in its own admin folder, not the main list. */
  autoGenerated: boolean;
  /** The customer email a recovery code is tied to (null for store-wide). */
  assignedEmail: string | null;
  /** Private (unlisted): valid at checkout for anyone who has the code, but
   *  never advertised on the storefront banner or coupon listings. */
  isPrivate: boolean;
  /** Audience: everyone ('all'), active members only, or non-members only. */
  memberScope: "all" | "members" | "non_members";
};

export type CouponInput = {
  code: string;
  discountType: "percent" | "fixed";
  discountValue: number;
  startsAt?: string | null;
  endsAt?: string | null;
  maxRedemptions?: number | null;
  active?: boolean;
  isPrivate?: boolean;
  memberScope?: "all" | "members" | "non_members";
};

type CouponRow = {
  id: string;
  code: string;
  discount_type: string;
  discount_value: number;
  starts_at: string | null;
  ends_at: string | null;
  max_redemptions: number | null;
  redemptions_count: number;
  active: boolean;
  created_at: string;
  assigned_email?: string | null;
  is_private?: boolean | null;
  member_scope?: string | null;
};

function mapCoupon(row: CouponRow): AdminCoupon {
  return {
    id: row.id,
    code: row.code,
    discountType: row.discount_type === "fixed" ? "fixed" : "percent",
    discountValue: Number(row.discount_value ?? 0),
    startsAt: row.starts_at,
    endsAt: row.ends_at,
    maxRedemptions: row.max_redemptions,
    redemptionsCount: Number(row.redemptions_count ?? 0),
    active: Boolean(row.active),
    createdAt: row.created_at,
    assignedEmail: row.assigned_email ?? null,
    autoGenerated: Boolean(row.assigned_email),
    isPrivate: Boolean(row.is_private),
    memberScope: row.member_scope === "members" ? "members" : row.member_scope === "non_members" ? "non_members" : "all",
  };
}

function validateCouponInput(input: CouponInput) {
  const code = normalizeCouponCode(input.code);
  if (!code) {
    throw new Error("Coupon code is required");
  }

  if (input.discountType !== "percent" && input.discountType !== "fixed") {
    throw new Error("Discount type must be percent or fixed");
  }

  const discountValue = Number(input.discountValue);
  if (!Number.isFinite(discountValue) || discountValue <= 0) {
    throw new Error("Discount value must be a positive number");
  }

  if (input.discountType === "percent" && discountValue > 100) {
    throw new Error("Percent discounts cannot exceed 100");
  }

  if (input.startsAt && input.endsAt && new Date(input.startsAt).getTime() > new Date(input.endsAt).getTime()) {
    throw new Error("Start date must be before end date");
  }

  if (input.maxRedemptions !== undefined && input.maxRedemptions !== null) {
    const maxRedemptions = Number(input.maxRedemptions);
    if (!Number.isFinite(maxRedemptions) || maxRedemptions < 1 || !Number.isInteger(maxRedemptions)) {
      throw new Error("Max redemptions must be a positive whole number");
    }
  }

  return code;
}

export async function listAdminCoupons(): Promise<AdminCoupon[]> {
  const { data, error } = await supabaseAdmin
    .from("coupons")
    .select("*")
    // Only the coupons YOU create (store-wide). Auto-generated per-customer
    // abandoned-cart recovery codes (assigned_email) live in their own folder —
    // see listCartRecoveryCoupons — so they never bury the codes you manage.
    .is("assigned_email", null)
    // Live coupons first, then newest — so the ones you create and turn on sit
    // at the top. (The admin UI also groups "Live now" first.)
    .order("active", { ascending: false })
    .order("created_at", { ascending: false });

  if (error) {
    throw error;
  }

  return (data ?? []).map((row) => mapCoupon(row as CouponRow));
}

export type CartRecoveryCouponList = {
  items: AdminCoupon[];
  total: number;
};

// The auto-generated abandoned-cart recovery codes, in their own bounded list.
// There can be thousands (one is minted per abandoned cart), so this returns
// only the most recent `limit` plus the true total for the folder header —
// never the whole set.
export async function listCartRecoveryCoupons(limit = 100): Promise<CartRecoveryCouponList> {
  const [listResult, countResult] = await Promise.all([
    supabaseAdmin
      .from("coupons")
      .select("*")
      .not("assigned_email", "is", null)
      .order("created_at", { ascending: false })
      .limit(limit),
    supabaseAdmin
      .from("coupons")
      .select("id", { count: "exact", head: true })
      .not("assigned_email", "is", null),
  ]);

  if (listResult.error) {
    throw listResult.error;
  }

  return {
    items: (listResult.data ?? []).map((row) => mapCoupon(row as CouponRow)),
    total: countResult.count ?? (listResult.data ?? []).length,
  };
}

export async function createAdminCoupon(input: CouponInput): Promise<AdminCoupon> {
  const code = validateCouponInput(input);

  const memberScope = input.memberScope === "members" || input.memberScope === "non_members" ? input.memberScope : "all";
  const baseRow = {
    code,
    discount_type: input.discountType,
    discount_value: input.discountValue,
    starts_at: input.startsAt ?? null,
    ends_at: input.endsAt ?? null,
    max_redemptions: input.maxRedemptions ?? null,
    active: input.active ?? true,
    redemptions_count: 0,
    created_at: new Date().toISOString(),
  };

  // is_private and member_scope are newer columns (coupon-private-flag.sql /
  // discount-rules-upgrade.sql). If a migration hasn't been applied yet, retry
  // without them so coupon creation never breaks — but ONLY when the admin
  // didn't ask for the restricted behavior: silently creating a "private" or
  // audience-scoped code as public/open would be the opposite of the intent.
  let { data, error } = await supabaseAdmin
    .from("coupons")
    .insert({ ...baseRow, is_private: Boolean(input.isPrivate), member_scope: memberScope })
    .select("*")
    .single();

  if (error && error.code !== "23505") {
    const message = String(error.message ?? "").toLowerCase();
    const missingColumn = error.code === "PGRST204"
      || ((message.includes("is_private") || message.includes("member_scope")) && (message.includes("does not exist") || message.includes("schema cache") || message.includes("could not find")));
    if (missingColumn) {
      if (input.isPrivate) {
        throw new Error("Private coupons need a one-time database update: run src/lib/sql/coupon-private-flag.sql in Supabase, then try again.");
      }
      if (memberScope !== "all") {
        throw new Error("Member-scoped coupons need a one-time database update: run src/lib/sql/discount-rules-upgrade.sql in Supabase, then try again.");
      }
      ({ data, error } = await supabaseAdmin
        .from("coupons")
        .insert(baseRow)
        .select("*")
        .single());
    }
  }

  if (error) {
    if (error.code === "23505") {
      throw new Error(`A coupon with code "${code}" already exists`);
    }
    throw error;
  }

  return mapCoupon(data as CouponRow);
}

export async function updateAdminCoupon(id: string, input: Partial<CouponInput>): Promise<AdminCoupon> {
  const updatePayload: Record<string, unknown> = {};

  if (input.code !== undefined) {
    updatePayload.code = normalizeCouponCode(input.code);
    if (!updatePayload.code) {
      throw new Error("Coupon code is required");
    }
  }

  if (input.discountType !== undefined) {
    if (input.discountType !== "percent" && input.discountType !== "fixed") {
      throw new Error("Discount type must be percent or fixed");
    }
    updatePayload.discount_type = input.discountType;
  }

  if (input.discountValue !== undefined) {
    const discountValue = Number(input.discountValue);
    if (!Number.isFinite(discountValue) || discountValue <= 0) {
      throw new Error("Discount value must be a positive number");
    }
    // Resolve the EFFECTIVE discount type — from this request if present, else
    // the coupon's stored type — so editing ONLY the value can't slip a percent
    // coupon past the >100 ceiling. (A percent coupon at 500 would zero out
    // merchandise while still charging tax/shipping.) Previously the guard only
    // ran when discountType was included in the same PATCH body.
    let effectiveType = input.discountType;
    if (!effectiveType) {
      const { data: existing } = await supabaseAdmin
        .from("coupons")
        .select("discount_type")
        .eq("id", id)
        .maybeSingle();
      effectiveType = existing?.discount_type === "percent" ? "percent" : "fixed";
    }
    if (effectiveType === "percent" && discountValue > 100) {
      throw new Error("Percent discounts cannot exceed 100");
    }
    updatePayload.discount_value = discountValue;
  }

  if (input.startsAt !== undefined) {
    updatePayload.starts_at = input.startsAt;
  }

  if (input.endsAt !== undefined) {
    updatePayload.ends_at = input.endsAt;
  }

  if (input.maxRedemptions !== undefined) {
    if (input.maxRedemptions !== null) {
      const maxRedemptions = Number(input.maxRedemptions);
      if (!Number.isFinite(maxRedemptions) || maxRedemptions < 1 || !Number.isInteger(maxRedemptions)) {
        throw new Error("Max redemptions must be a positive whole number");
      }
      updatePayload.max_redemptions = maxRedemptions;
    } else {
      updatePayload.max_redemptions = null;
    }
  }

  if (input.active !== undefined) {
    updatePayload.active = input.active;
  }

  if (input.memberScope !== undefined) {
    updatePayload.member_scope = input.memberScope === "members" || input.memberScope === "non_members" ? input.memberScope : "all";
  }

  const { data, error } = await supabaseAdmin
    .from("coupons")
    .update(updatePayload)
    .eq("id", id)
    .select("*")
    .single();

  if (error) {
    if (error.code === "23505") {
      throw new Error("A coupon with that code already exists");
    }
    throw error;
  }

  return mapCoupon(data as CouponRow);
}

export async function deleteAdminCoupon(id: string) {
  const { error } = await supabaseAdmin.from("coupons").delete().eq("id", id);
  if (error) {
    throw error;
  }
}
