export type Product = {
  slug: string;
  name: string;
  category: string;
  price: string;
  stockStatus: "In Stock" | "Limited" | "Reserved";
  batchNumber: string;
  purityResult?: string;
  description: string;
  image: string;
  testingDate: string;
  labName: string;
  coaUrl: string;
  molecularFormula?: string;
};

export type CoaRecord = {
  slug: string;
  productName: string;
  category: string;
  batchNumber: string;
  purityResult: string;
  testingDate: string;
  labName: string;
  coaUrl: string;
};

export const products: Product[] = [
  /* ── Research Peptides — Comprehensive Compounds ─────────────────────── */
  {
    slug: "bpc-157-10mg",
    name: "BPC-157",
    category: "Research Peptides",
    price: "$44.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718A",
    purityResult: "99.8%",
    description: "Synthetic pentadecapeptide for research into gastrointestinal protection, angiogenesis, and tissue repair mechanisms.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-10",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C62H98N16O22",
  },
  {
    slug: "glp-1-15mg",
    name: "GLP-1",
    category: "Research Peptides",
    price: "$64.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718B",
    purityResult: "99.6%",
    description: "Glucagon-like peptide-1 analog for metabolic pathway research and glucose homeostasis investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-11",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C172H265N43O60",
  },
  {
    slug: "glp-3-10mg",
    name: "GLP-3",
    category: "Research Peptides",
    price: "$64.99",
    stockStatus: "Limited",
    batchNumber: "VL-0718C",
    purityResult: "99.5%",
    description: "Glucagon-like peptide-3 research compound for metabolic regulation and endocrine signaling studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-12",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C143H227N39O50",  },
  {
    slug: "glp-2-10mg",
    name: "GLP-2",
    category: "Research Peptides",
    price: "$64.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718D",
    purityResult: "99.7%",
    description: "Glucagon-like peptide-2 for intestinal epithelial research and mucosal immunity pathway characterization.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-13",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C131H207N35O46",
  },
  {
    slug: "hgh-191aa-24iu",
    name: "HGH 191AA",
    category: "Research Peptides",
    price: "$59.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718E",
    purityResult: "99.9%",
    description: "Human growth hormone (191 amino acid) for somatotropic research and growth factor signaling investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-14",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C990H1529N263O300S7",
  },
  {
    slug: "nad-plus-500mg",
    name: "NAD+",
    category: "Research Peptides",
    price: "$74.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718F",
    purityResult: "99.4%",
    description: "Nicotinamide adenine dinucleotide for bioenergetics research and cellular metabolism pathway studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-15",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C21H27N7O14P2",
  },
  {
    slug: "klow-80mg",
    name: "KLOW",
    category: "Research Peptides",
    price: "$139.99",
    stockStatus: "Limited",
    batchNumber: "VL-0718G",
    purityResult: "99.5%",
    description: "Proprietary research peptide for metabolic investigation and cellular signaling pathway characterization.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-16",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C44H68N14O14",  },
  {
    slug: "bpc-157-tb-500-blend",
    name: "BPC-157 + TB-500",
    category: "Research Peptides",
    price: "$119.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718H",
    purityResult: "99.7%",
    description: "Synergistic peptide blend combining BPC-157 and thymosin beta-4 for tissue repair and recovery research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-17",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C62H98N16O22 + C60H99N17O20",
  },
  {
    slug: "hcg-5000iu",
    name: "HCG",
    category: "Research Peptides",
    price: "$84.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718I",
    purityResult: "99.6%",
    description: "Human chorionic gonadotropin for endocrine signaling research and reproductive pathway investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-18",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C2735H4316N730O901S15",
  },
  {
    slug: "reconstitution-water-3ml",
    name: "Reconstitution Water (0.9% Benzyl Alcohol)",
    category: "Solvents & Solutions",
    price: "$9.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718J",
    purityResult: "99.9%",
    description: "Sterile reconstitution solution for peptide preparation with bacteriostatic properties.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-19",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "H2O + C7H8O",
  },
  {
    slug: "lipo-c-10ml",
    name: "Lipo-C",
    category: "Research Peptides",
    price: "$59.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718K",
    purityResult: "99.3%",
    description: "Lipotropic research compound for metabolic pathway investigation and weight management research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-20",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C10H15N4O2 + C7H8NO2",
  },
  {
    slug: "ghrp-2-5mg",
    name: "GHRP-2",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "Limited",
    batchNumber: "VL-0718L",
    purityResult: "99.5%",
    description: "Growth hormone releasing peptide-2 for somatotropic research and growth hormone secretion studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-21",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C43H56N12O6",  },
  {
    slug: "ghrp-6-10mg",
    name: "GHRP-6",
    category: "Research Peptides",
    price: "$59.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718M",
    purityResult: "99.6%",
    description: "Growth hormone releasing peptide-6 for growth hormone axis research and appetite regulation studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-22",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C46H56N12O6",
  },
  {
    slug: "cagrilintide-10mg",
    name: "Cagrilintide",
    category: "Research Peptides",
    price: "$84.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718N",
    purityResult: "99.4%",
    description: "Novel peptide agonist for metabolic and appetite regulation research applications.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-23",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C190H291N49O60",
  },
  {
    slug: "ghk-cu-50mg",
    name: "GHK-Cu",
    category: "Research Peptides",
    price: "$59.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718O",
    purityResult: "99.7%",
    description: "Copper peptide complex for tissue regeneration and collagen synthesis research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-24",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C14H21N5O5Cu",
  },
  {
    slug: "tesamorelin-10mg",
    name: "Tesamorelin",
    category: "Research Peptides",
    price: "$74.99",
    stockStatus: "Limited",
    batchNumber: "VL-0718P",
    purityResult: "99.5%",
    description: "Growth hormone releasing hormone analog for body composition and metabolic research studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-25",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C66H103N17O14",  },
  {
    slug: "glow-70mg",
    name: "GLOW",
    category: "Research Peptides",
    price: "$119.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718Q",
    purityResult: "99.6%",
    description: "Proprietary skincare peptide research compound for dermal health and aesthetic research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-26",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C64H102N18O19",
  },
  {
    slug: "5-amino-1mq-5mg",
    name: "5-Amino-1MQ",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718R",
    purityResult: "99.3%",
    description: "Metabolic research compound for mitochondrial function and energy expenditure investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-27",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C9H10N4O",
  },
  {
    slug: "reconstitution-water-30ml",
    name: "Reconstitution Water (0.9% Benzyl Alcohol) — 30mL",
    category: "Solvents & Solutions",
    price: "$24.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718S",
    purityResult: "99.9%",
    description: "Large format sterile reconstitution solution for bulk peptide preparation.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-28",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "H2O + C7H8O",
  },
  {
    slug: "cerebrolysin-60mg",
    name: "Cerebrolysin",
    category: "Research Peptides",
    price: "$99.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718T",
    purityResult: "99.4%",
    description: "Neuropeptide complex for cognitive function and brain health research applications.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-29",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C45H71N13O16",
  },
  {
    slug: "cjc-1295-no-dac-10mg",
    name: "CJC-1295 No DAC",
    category: "Research Peptides",
    price: "$74.99",
    stockStatus: "Limited",
    batchNumber: "VL-0718U",
    purityResult: "99.5%",
    description: "Growth hormone releasing hormone analog for growth factor research and longevity studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-30",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C72H107N19O19",  },
  {
    slug: "cjc-1295-ipamorelin-blend",
    name: "CJC-1295 No DAC + Ipamorelin",
    category: "Research Peptides",
    price: "$74.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718V",
    purityResult: "99.6%",
    description: "Synergistic GHRH and GHRP blend for comprehensive growth hormone axis research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-07-31",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C72H107N19O19 + C38H49N9O5",
  },
  {
    slug: "dsip-10mg",
    name: "DSIP",
    category: "Research Peptides",
    price: "$39.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718W",
    purityResult: "99.3%",
    description: "Delta sleep-inducing peptide for circadian rhythm and sleep quality research investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-01",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C39H43N9O6",
  },
  {
    slug: "epithalon-10mg",
    name: "Epithalon",
    category: "Research Peptides",
    price: "$39.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718X",
    purityResult: "99.4%",
    description: "Telomerase-activating peptide for longevity research and cellular senescence investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-02",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C14H21N5O6",
  },
  {
    slug: "glutathione-1500mg",
    name: "Glutathione",
    category: "Research Peptides",
    price: "$69.99",
    stockStatus: "Limited",
    batchNumber: "VL-0718Y",
    purityResult: "99.5%",
    description: "Tripeptide antioxidant for oxidative stress research and cellular protection studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-03",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C10H17N3O6S",  },
  {
    slug: "igf-1-lr3-1mg",
    name: "IGF-1 LR3",
    category: "Research Peptides",
    price: "$69.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0718Z",
    purityResult: "99.6%",
    description: "Insulin-like growth factor-1 long R3 for tissue growth and protein synthesis research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-04",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C387H603N103O114S17",
  },
  {
    slug: "thymosin-alpha-1-5mg",
    name: "Thymosin Alpha-1",
    category: "Research Peptides",
    price: "$59.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818A",
    purityResult: "99.7%",
    description: "Immune-modulating peptide for immunological function and thymic factor research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-05",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C108H151N31O32S2",
  },
  {
    slug: "selank-10mg",
    name: "Selank",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818B",
    purityResult: "99.4%",
    description: "Anxiolytic peptide for neurochemical research and stress response pathway investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-06",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C20H30N6O7",
  },
  {
    slug: "semax-10mg",
    name: "Semax",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818C",
    purityResult: "99.5%",
    description: "Nootropic peptide for cognitive enhancement research and neuroprotection studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-07",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C27H36N6O6",
  },
  {
    slug: "snap-8-10mg",
    name: "SNAP-8",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "Limited",
    batchNumber: "VL-0818D",
    purityResult: "99.3%",
    description: "Neuropeptide for muscle relaxation and anti-aging research applications.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-08",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C46H71N15O11",  },
  {
    slug: "ss-31-10mg",
    name: "SS-31",
    category: "Research Peptides",
    price: "$74.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818E",
    purityResult: "99.6%",
    description: "Mitochondrial-targeting peptide for cellular energy optimization research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-09",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C29H43N7O10",
  },
  {
    slug: "pt-141-10mg",
    name: "PT-141",
    category: "Research Peptides",
    price: "$39.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818F",
    purityResult: "99.4%",
    description: "Melanocortin agonist for sexual function and reproductive research investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-10",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C16H22N4O3",
  },
  {
    slug: "pinealon-10mg",
    name: "Pinealon",
    category: "Research Peptides",
    price: "$99.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818G",
    purityResult: "99.5%",
    description: "Pineal peptide for sleep cycle regulation and circadian rhythm research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-11",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C16H23N3O4",
  },
  {
    slug: "mt-2-melanotan-ii-10mg",
    name: "MT-2 (Melanotan II)",
    category: "Research Peptides",
    price: "$39.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818H",
    purityResult: "99.3%",
    description: "Melanocortin receptor agonist for pigmentation and dermal research applications.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-12",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C12H16N4O2",
  },
  {
    slug: "mots-c-10mg",
    name: "MOTS-c",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "Limited",
    batchNumber: "VL-0818I",
    purityResult: "99.6%",
    description: "Mitochondrial peptide for metabolic regulation and exercise response research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-13",
    labName: "Quantum Reference Labs",
    coaUrl: "/demo-coa.pdf",    molecularFormula: "C72H111N19O22",  },
  {
    slug: "ipamorelin-10mg",
    name: "Ipamorelin",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818J",
    purityResult: "99.4%",
    description: "Selective growth hormone secretagogue for growth factor research and muscle development studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-14",
    labName: "Vanta Independent Testing Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C38H49N9O5",
  },
  {
    slug: "kisspeptin-10mg",
    name: "Kisspeptin",
    category: "Research Peptides",
    price: "$89.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818K",
    purityResult: "99.5%",
    description: "Reproductive axis peptide for gonadotropin regulation and fertility research investigations.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-15",
    labName: "Apex Verification Services",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C54H81N19O12",
  },
  {
    slug: "kpv-10mg",
    name: "KPV",
    category: "Research Peptides",
    price: "$49.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818L",
    purityResult: "99.3%",
    description: "Anti-inflammatory tripeptide for immune response and inflammatory pathway research.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-16",
    labName: "North Meridian Analytical Labs",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C9H16N4O5",
  },
  {
    slug: "l-carnitine-6000mg",
    name: "L-Carnitine",
    category: "Research Peptides",
    price: "$59.99",
    stockStatus: "In Stock",
    batchNumber: "VL-0818M",
    purityResult: "99.6%",
    description: "Amino acid derivative for metabolic efficiency and energy production research studies.",
    image: "/images/vantalabs.png",
    testingDate: "2026-08-17",
    labName: "Stratum Analytical Group",
    coaUrl: "/demo-coa.pdf",
    molecularFormula: "C7H15NO3",
  },
];

export const coaRecords: CoaRecord[] = products.map((product) => ({
  slug: product.slug,
  productName: product.name,
  category: product.category,
  batchNumber: product.batchNumber,
  purityResult: product.purityResult ?? "Pending",
  testingDate: product.testingDate,
  labName: product.labName,
  coaUrl: product.coaUrl,
}));
