-- =============================================================================
-- BASELINE CAPTURE — live database functions that were NOT in source control
-- =============================================================================
--
-- Captured verbatim from the live Supabase project (mlpimwgkwuqpsvsrlpqv) on
-- 2026-08-25 via pg_get_functiondef(), during the final certification audit.
--
-- WHY THIS FILE EXISTS
--
-- Three functions existed only in the production database. Nothing in this
-- repository defined them. All three are safety-critical, and all three are
-- repairs for defects found in live data:
--
--   create_partner_application  the atomic partner+ambassador creation that
--                               replaced two sequential inserts (the BRUTUS
--                               orphan defect)
--   affiliate_balances          server-side aggregation of what each partner is
--                               owed, which replaced an unbounded client-side
--                               select exposed to the PostgREST row cap
--   rls_auto_enable             an event trigger that enables RLS on every new
--                               public table -- the reason all 68 tables have
--                               RLS rather than only the ones someone
--                               remembered
--
-- Had the database been rebuilt from this repository, all three protections
-- would have disappeared silently and the defects they fix would have returned.
--
-- HOW TO USE THIS FILE
--
-- This is a BASELINE, not a migration to run blindly. It records what production
-- actually contained at capture time so that later changes are reviewable as
-- diffs against a known state. `CREATE OR REPLACE` makes re-applying it a no-op
-- when production already matches.
--
-- Do not edit this file to change behaviour. Add a new, separately reviewable
-- SQL file for any change, so the diff shows what moved and why.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- validate_referral_code(input_code text) -> jsonb
--
-- Resolves a referral code to its ambassador. Two properties matter and are
-- verified in production:
--   * it returns customer_discount_percent, so the browser can show the
--     ambassador's real rate instead of falling back to the program default
--     (the "15% ambassador, 10% shown" defect)
--   * it filters status = 'approved', so a partner the owner put on hold has an
--     inert code
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.validate_referral_code(input_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'valid', true,
    'referral_code', a.referral_code,
    'ambassador_id', a.id,
    'ambassador_name', a.name,
    -- NULL is meaningful and passes through as null: "no override, use the
    -- program default". Coercing it to 0 would hand every inheriting
    -- ambassador a 0% customer discount.
    'customer_discount_percent', a.customer_discount_percent
  )
  into result
  from public.ambassadors a
  where a.referral_code = upper(trim(input_code))
    and a.status = 'approved'
  limit 1;

  if result is null then
    return jsonb_build_object('valid', false);
  end if;

  return result;
end;
$function$;


-- -----------------------------------------------------------------------------
-- create_partner_application(...) -> jsonb
--
-- BOTH ROWS OR NEITHER. Replaced two sequential inserts whose first committed on
-- its own, leaving an applicant with a partners row and no ambassadors row --
-- approved in the admin, dead link in the wild.
--
-- KNOWN LIMITATION AT CAPTURE TIME (audit finding F-009): identity is matched by
-- auth_user_id alone. An ambassador the admin pre-added by email, with no auth
-- account yet, is not recognised when that person later signs up and applies.
-- The ambassadors insert then violates ambassadors_email_key and the whole
-- application rolls back, so the applicant can never apply. Recorded here as the
-- baseline; the repair lands in a separate file.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_partner_application(
  p_id uuid,
  p_auth_user_id uuid,
  p_name text,
  p_email text,
  p_referral_code text,
  p_commission_percent numeric,
  p_applicant jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  existing record;
  now_ts timestamptz := now();
begin
  -- Already applied? Hand back what exists. Never a second identity, never a
  -- rewrite of rates the owner may have configured since.
  select id, status, referral_code into existing
  from public.partners
  where auth_user_id = p_auth_user_id
  limit 1;

  if found then
    return jsonb_build_object(
      'partner_id', existing.id,
      'status', existing.status,
      'referral_code', existing.referral_code,
      'created', false
    );
  end if;

  insert into public.partners (
    id, name, email, referral_code, status, commission_percent, auth_user_id,
    invited_at, updated_at,
    first_name, last_name, phone, social, follower_count, preferred_referral_code
  ) values (
    p_id, p_name, p_email, p_referral_code, 'pending', p_commission_percent, p_auth_user_id,
    now_ts, now_ts,
    p_applicant->>'first_name', p_applicant->>'last_name', p_applicant->>'phone',
    p_applicant->>'social', (p_applicant->>'follower_count')::int,
    p_applicant->>'preferred_referral_code'
  );

  insert into public.ambassadors (
    id, name, email, referral_code, status, commission_percent, auth_user_id,
    invited_at, updated_at,
    first_name, last_name, phone, social, follower_count, preferred_referral_code
  ) values (
    p_id, p_name, p_email, p_referral_code, 'pending', p_commission_percent, p_auth_user_id,
    now_ts, now_ts,
    p_applicant->>'first_name', p_applicant->>'last_name', p_applicant->>'phone',
    p_applicant->>'social', (p_applicant->>'follower_count')::int,
    p_applicant->>'preferred_referral_code'
  );

  return jsonb_build_object(
    'partner_id', p_id, 'status', 'pending',
    'referral_code', p_referral_code, 'created', true
  );
end;
$function$;


-- -----------------------------------------------------------------------------
-- affiliate_balances() -> table
--
-- One row per ambassador, computed in the database. The payout queue previously
-- summed every approved_for_payout row fetched over PostgREST; above the
-- project's db-max-rows that page comes back short with no error, and the owner
-- is shown less than they owe. Aggregating server-side means the row cap only
-- bites above the number of PARTNERS, not the number of orders.
--
-- Note for the audit: this reads referral_orders, while the commissions table
-- also exists and is empty. Which of the two is authoritative for money is an
-- open question tracked in the audit ledger.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.affiliate_balances()
 RETURNS TABLE(
   ambassador_id uuid,
   pending_amount numeric,
   approved_amount numeric,
   paid_amount numeric,
   lifetime_earned numeric,
   approved_count bigint,
   earliest_approved_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  select
    ro.ambassador_id,
    coalesce(sum(ro.commission_amount) filter (where ro.payment_status = 'pending'), 0)              as pending_amount,
    coalesce(sum(ro.commission_amount) filter (where ro.payment_status = 'approved_for_payout'), 0)  as approved_amount,
    coalesce(sum(ro.commission_amount) filter (where ro.payment_status = 'paid'), 0)                 as paid_amount,
    -- Lifetime EARNED excludes clawed-back states, matching isEarnedCommission.
    coalesce(sum(ro.commission_amount) filter (
      where lower(coalesce(ro.payment_status, '')) not in ('reversed', 'voided', 'manual_review')
    ), 0)                                                                                            as lifetime_earned,
    count(*) filter (where ro.payment_status = 'approved_for_payout')                                as approved_count,
    min(ro.approved_for_payout_at) filter (where ro.payment_status = 'approved_for_payout')          as earliest_approved_at
  from public.referral_orders ro
  where ro.ambassador_id is not null
  group by ro.ambassador_id;
$function$;


-- -----------------------------------------------------------------------------
-- rls_auto_enable() -- event trigger function
--
-- Enables row level security on every new table created in `public`. This is why
-- RLS coverage is 68/68 rather than "the tables someone remembered". The event
-- trigger itself must also exist; see the statement below the function.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;
