create unique index if not exists orders_payment_id_uniq on public.orders (payment_id) where (payment_id is not null);
create unique index if not exists orders_provider_event_id_uniq on public.orders (provider_event_id) where (provider_event_id is not null);
create unique index if not exists idx_orders_order_number on public.orders (order_number) where (order_number is not null);
create unique index if not exists idx_orders_shippo_order_id on public.orders (shippo_order_id) where (shippo_order_id is not null);
create unique index if not exists idx_ambassador_wallet_redemption_once on public.ambassador_wallet_ledger (order_id) where (reason = 'redemption'::text);
create unique index if not exists idx_abandoned_carts_session_active on public.abandoned_carts (session_id) where (status = 'active'::text);
create unique index if not exists idx_abandoned_cart_emails_cart_stage on public.abandoned_cart_emails (abandoned_cart_id, stage);
create unique index if not exists idx_bis_unique_pending on public.back_in_stock_requests (product_slug, coalesce(variant_id,''::text), email) where (notified = false);
create unique index if not exists idx_product_doses_product_slug_suffix on public.product_doses (product_id, slug_suffix);
create unique index if not exists idx_products_slug on public.products (slug);
create unique index if not exists shipping_package_presets_single_default on public.shipping_package_presets (is_default) where is_default;
create unique index if not exists email_campaign_recipients_campaign_id_email_key on public.email_campaign_recipients (campaign_id, email);
create unique index if not exists order_amount_backfills_order_id_column_name_key on public.order_amount_backfills (order_id, column_name);
create unique index if not exists customer_memberships_veyra_membership_id_key on public.customer_memberships (veyra_membership_id) where (veyra_membership_id is not null);
create unique index if not exists express_checkout_intents_session_key on public.express_checkout_intents (veyra_session_id) where (veyra_session_id is not null);
create unique index if not exists wishlist_items_user_id_product_slug_key on public.wishlist_items (user_id, product_slug);
create unique index if not exists inventory_items_product_id_key on public.inventory_items (product_id);
create unique index if not exists fulfillment_payouts_order_id_key on public.fulfillment_payouts (order_id);
create unique index if not exists customer_preferences_referral_code_key on public.customer_preferences (referral_code);
create unique index if not exists ambassadors_email_key on public.ambassadors (email);
create unique index if not exists ambassadors_referral_code_key on public.ambassadors (referral_code);
create unique index if not exists partners_referral_code_key on public.partners (referral_code);
create unique index if not exists partners_auth_user_id_key on public.partners (auth_user_id);
create unique index if not exists coupons_code_key on public.coupons (code);
create unique index if not exists membership_tiers_slug_key on public.membership_tiers (slug);
create unique index if not exists order_shipments_order_id_key on public.order_shipments (order_id);
create unique index if not exists admin_credentials_username_key on public.admin_credentials (username);
create unique index if not exists admin_sessions_token_hash_key on public.admin_sessions (token_hash);

do $$ begin
  alter table public.admin_credentials add constraint pc_admin_role check (role = any (array['staff','manager','super_admin']));
exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.ambassadors add constraint pc_amb_cdp check ((customer_discount_percent is null) or (customer_discount_percent >= 0 and customer_discount_percent < 100)) not valid; exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.ambassadors add constraint pc_amb_status check (status = any (array['pending','approved','disabled','rejected','info_requested'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.partners add constraint pc_par_cdp check ((customer_discount_percent is null) or (customer_discount_percent >= 0 and customer_discount_percent < 100)) not valid; exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.partners add constraint pc_par_status check (status = any (array['pending','approved','disabled','rejected','info_requested'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.coa_records add constraint pc_coa_status check (status = any (array['draft','published','archived'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.coupons add constraint pc_coup_scope check (member_scope = any (array['all','members','non_members'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.express_checkout_intents add constraint pc_eci_amt check (amount_cents >= 50); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.inventory_reservations add constraint pc_ir_qty check (quantity > 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.order_amount_backfills add constraint pc_oab_basis check (basis = any (array['recorded','reconstructed'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.order_email_log add constraint pc_oel_status check (status = any (array['sending','sent','failed'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.order_items add constraint pc_oi_cost check ((unit_cost_cents is null) or (unit_cost_cents >= 0)); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.orders add constraint pc_ord_spf check (shipping_protection_fee >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.product_doses add constraint pc_pd_incoming check (incoming_quantity >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.products add constraint pc_p_incoming check (incoming_quantity >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.referral_orders add constraint pc_ro_amt check (amount_paid >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.referral_orders add constraint pc_ro_comm check (commission_amount >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.referral_orders add constraint pc_ro_cd check (customer_discount >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.referral_orders add constraint pc_ro_os check (original_subtotal >= 0); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.referral_orders add constraint pc_ro_ps check (payment_status = any (array['paid','refunded','partially_refunded'])); exception when duplicate_object or duplicate_table then null; end $$;
do $$ begin alter table public.referral_orders add constraint pc_ro_pos check (payout_status = any (array['unpaid','paid','void'])); exception when duplicate_object or duplicate_table then null; end $$;
