// Shared fixture table: see template-standards.test.ts.
export const URL_ = "https://www.vantalabsresearch.com/account";
const ITEMS = [{ name: "BPC-157 5mg", quantity: 2, lineTotal: 119.98 }];

/** Representative input for every exported template, keyed by name. */
export const INPUTS: Record<string, unknown> = {
  couponAnnouncementTemplate: { headline: "10% off", code: "SAVE10", discountLabel: "10% off", message: "Enjoy.", endsAt: "2026-09-30T00:00:00Z", shopUrl: URL_ },
  accountConfirmationTemplate: { name: "Zain", confirmUrl: URL_ },
  accountConfirmationResendTemplate: { name: "Zain", confirmUrl: URL_ },
  passwordResetTemplate: { name: "Zain", resetUrl: URL_ },
  orderConfirmationTemplate: { customerName: "Zain", orderId: "VL-1001", items: ITEMS, subtotal: 119.98, shipping: 5, total: 124.98, orderUrl: URL_, shippingAddress: "1 Nowhere Lane" },
  reimbursementRecordedTemplate: { customerName: "Zain", orderId: "VL-1001", amount: 25, supportEmail: "support@vantalabsresearch.com" },
  refundConfirmationTemplate: { customerName: "Zain", orderId: "VL-1001", refundAmount: 25, isFullRefund: false, supportEmail: "support@vantalabsresearch.com" },
  manualPaymentReceivedTemplate: { customerName: "Zain", orderNumber: "VL-1001", amount: 124.98, paymentMethod: "Zelle" },
  newPaymentToVerifyTemplate: { orderNumber: "VL-1001", customerName: "Zain", customerEmail: "z@example.test", amount: 124.98, paymentMethod: "Zelle", transactionId: "T-1", adminUrl: URL_ },
  manualPaymentRejectedTemplate: { customerName: "Zain", orderNumber: "VL-1001", reason: "Amount mismatch", resubmitUrl: URL_ },
  shippingUpdateTemplate: { customerName: "Zain", orderId: "VL-1001", status: "shipped", carrier: "USPS", trackingNumber: "9400111", trackingUrl: URL_ },
  replacementOrderTemplate: { customerName: "Zain", originalOrderNumber: "VL-1001", replacementOrderNumber: "VL-1002", items: [{ name: "BPC-157 5mg", quantity: 1 }], supportEmail: "support@vantalabsresearch.com", orderUrl: URL_ },
  deliveryConfirmationTemplate: { customerName: "Zain", orderId: "VL-1001", shopUrl: URL_ },
  ambassadorInviteTemplate: { name: "Zain", inviteUrl: URL_, commissionPercent: 20 },
  ambassadorApplicationReceivedTemplate: { name: "Zain" },
  ambassadorApprovedTemplate: { name: "Zain", referralCode: "ZAIN", dashboardUrl: URL_, commissionPercent: 20, personalDiscountPercent: 20, referralDiscountPercent: 10, minimumQualifyingOrder: 100 },
  ambassadorPayoutSentTemplate: { name: "Zain", amount: 250, method: "PayPal", handle: "z@example.test", orderCount: 5, dashboardUrl: URL_ },
  orderCancelledTemplate: { customerName: "Zain", orderId: "VL-1001", reason: "Out of stock", refundNote: "Refunded in full.", supportEmail: "support@vantalabsresearch.com" },
  emailChangeConfirmationTemplate: { name: "Zain", newEmail: "new@example.com", confirmUrl: URL_ },
  ambassadorInfoRequestedTemplate: { name: "Zain", supportEmail: "support@vantalabsresearch.com", applicationUrl: URL_ },
  ambassadorDeniedTemplate: { name: "Zain" },
  commissionEarnedTemplate: { name: "Zain", commissionAmount: 24, unpaidBalance: 120, referralCode: "ZAIN", dashboardUrl: URL_ },
  newAmbassadorApplicationTemplate: { applicantName: "Zain", applicantEmail: "z@example.test", adminUrl: URL_ },
  referralCodeAssignedTemplate: { name: "Zain", referralCode: "ZAIN", referralLink: URL_, commissionPercent: 20, dashboardUrl: URL_ },
  membershipWelcomeTemplate: { name: "Zain", tierName: "Vault" },
  membershipTrialConfirmationTemplate: { name: "Zain", tierName: "Vault", introChargeCents: 100, remainderCents: 900, remainderChargeDate: "2026-09-30", monthlyPriceCents: 1000 },
  membershipRemainderReminderTemplate: { name: "Zain", remainderCents: 900, chargeDate: "2026-09-30" },
  membershipRemainderReceiptTemplate: { name: "Zain", remainderCents: 900, nextBillingDate: "2026-10-30", monthlyPriceCents: 1000 },
  membershipRenewalReminderTemplate: { name: "Zain", monthlyPriceCents: 1000, chargeDate: "2026-09-30" },
  membershipRenewalReceiptTemplate: { name: "Zain", monthlyPriceCents: 1000, nextBillingDate: "2026-10-30" },
  membershipSignupReceiptTemplate: { name: "Zain", tierName: "Vault", amountCents: 1000, billingCycle: "monthly", nextBillingDate: "2026-10-30", autoRenews: true },
  membershipPaymentFailedTemplate: { name: "Zain", amountCents: 1000, updatePaymentUrl: URL_ },
  membershipBenefitsMonthlyTemplate: { name: "Zain", headline: "Your perks", bodyHtml: "<p>Enjoy.</p>", ctaLabel: "Shop", ctaUrl: URL_ },
  membershipBirthdayTemplate: { name: "Zain", bonusPoints: 500, rewardUrl: URL_ },
  membershipWinBackTemplate: { name: "Zain", tierName: "Vault", offerPercent: 20, resubscribeUrl: URL_ },
  newProductLaunchTemplate: { name: "Zain", productName: "BPC-157", productUrl: URL_ },
  backInStockTemplate: { name: "Zain", productName: "BPC-157", productUrl: URL_ },
  cartRecoveryT30mTemplate: { name: "Zain", items: [{ name: "BPC-157", quantity: 1 }], cartValueCents: 11998, restoreUrl: URL_ },
  cartRecoveryT12hTemplate: { name: "Zain", items: [{ name: "BPC-157", quantity: 1 }], cartValueCents: 11998, restoreUrl: URL_ },
  cartRecoveryT24hTemplate: { name: "Zain", items: [{ name: "BPC-157", quantity: 1 }], cartValueCents: 11998, restoreUrl: URL_ },
  cartRecoveryT72hTemplate: { name: "Zain", items: [{ name: "BPC-157", quantity: 1 }], cartValueCents: 11998, restoreUrl: URL_, couponCode: "COMEBACK", discountPercent: 5, expiresAt: "September 30, 2026" },
  contactFormNotificationTemplate: { firstName: "Zain", lastName: "M", email: "z@example.test", orderNumber: "VL-1001", subject: "Question", message: "Hello" },
  contactFormAutoReplyTemplate: { firstName: "Zain", subject: "Question", message: "Hello" },
  wholesaleInquiryNotificationTemplate: { firstName: "Zain", lastName: "M", email: "z@example.test", phone: "+1", organization: "Lab", volume: "100", products: "BPC", message: "Hello" },
  wholesaleInquiryAutoReplyTemplate: { firstName: "Zain" },
  campaignTemplate: { subject: "News", previewText: "News", headline: "News", body: "<p>Hi</p>", promoCode: "SAVE10", ctaLabel: "Shop", ctaUrl: URL_, offerTerms: "Your gift: a free GHK-Cu on any order of $60 or more, through October 4, 2026. One per customer." },
};
