"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  groupSize,
  isPromotionScheduled,
  promotionHeadline,
  storefrontDescription,
  type BxgyPromotion,
} from "@/lib/bxgy-engine";
import { normalizeBxgyPromotion } from "@/lib/bxgy-config";

// ---------------------------------------------------------------------------
// THE PROMOTION CENTRE.
//
// Six promotions, one editor, because they are six configurations of one rule
// (bxgy-engine.ts) rather than six features. Every field on this form is a
// field on BxgyPromotion, and every sentence it shows a shopper — the headline,
// the storefront line — is generated by the same engine functions the cart and
// the product page call, so what an admin previews here is literally what a
// customer reads.
// ---------------------------------------------------------------------------

type PromotionRow = BxgyPromotion & { liveNow?: boolean; scheduledNow?: boolean };

/** ISO ⇄ the value a datetime-local input wants, in the admin's own timezone. */
function toLocalInputValue(iso: string | null): string {
  if (!iso) return "";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function fromLocalInputValue(value: string): string | null {
  if (!value) return null;
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString();
}

function slugsToText(slugs: string[]): string {
  return slugs.join(", ");
}

function textToSlugs(value: string): string[] {
  return Array.from(new Set(
    value.split(/[,\n]/).map((entry) => entry.trim().toLowerCase()).filter(Boolean),
  ));
}

function limitToText(value: number | null): string {
  return value === null ? "" : String(value);
}

function textToLimit(value: string): number | null {
  const trimmed = value.trim();
  if (!trimmed) return null; // blank means unlimited, never zero
  const parsed = Number(trimmed);
  if (!Number.isFinite(parsed) || parsed < 0) return null;
  return Math.floor(parsed);
}

export function AdminPromotionsClient({ initialBuy3Get1Enabled }: { initialBuy3Get1Enabled: boolean }) {
  const [promotions, setPromotions] = useState<PromotionRow[] | null>(null);
  const [productSlugs, setProductSlugs] = useState<string[]>([]);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/admin/promotions", { cache: "no-store" });
      const json = await response.json();
      if (!response.ok || !json.success) throw new Error(json.error ?? "Unable to load promotions");
      const rows: PromotionRow[] = (Array.isArray(json.bxgyPromotions) ? json.bxgyPromotions : [])
        .map((entry: unknown) => {
          const normalized = normalizeBxgyPromotion(entry);
          if (!normalized) return null;
          const extras = entry as { liveNow?: boolean; scheduledNow?: boolean };
          return { ...normalized, liveNow: extras.liveNow, scheduledNow: extras.scheduledNow };
        })
        .filter(Boolean) as PromotionRow[];
      setPromotions(rows);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Unable to load promotions");
      setPromotions([]);
    }
  }, []);

  useEffect(() => {
    (async () => { await load(); })();
  }, [load]);

  // Slug suggestions for the eligibility fields. Purely a convenience — the
  // fields accept any slug, because a product can be added after a promotion is
  // configured for it.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const response = await fetch("/api/catalog/products", { cache: "no-store" });
        if (!response.ok) return;
        const json = await response.json() as { success?: boolean; products?: Array<{ slug?: string }> };
        if (cancelled || !json.success || !Array.isArray(json.products)) return;
        setProductSlugs(json.products.map((product) => String(product.slug ?? "")).filter(Boolean).sort());
      } catch {
        // A missing suggestion list is cosmetic; the fields still work.
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const update = (id: string, patch: Partial<BxgyPromotion>) => {
    setPromotions((current) => (current ?? []).map((promotion) => (
      promotion.id === id ? { ...promotion, ...patch } : promotion
    )));
  };

  const save = async (promotion: PromotionRow) => {
    setSavingId(promotion.id);
    setMessage(null);
    setError(null);
    try {
      const response = await fetch("/api/admin/promotions", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        // One promotion per request. The endpoint merges over the stored list,
        // so saving one can never blank the others.
        body: JSON.stringify({ promotions: [promotion] }),
      });
      const json = await response.json();
      if (!response.ok || !json.success) throw new Error(json.error ?? "Save failed");
      setMessage(`${promotion.name} saved.`);
      await load();
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : "Save failed");
      await load(); // never leave the form showing something that was not stored
    } finally {
      setSavingId(null);
    }
  };

  if (promotions === null) {
    return <section className="vl-panel rounded-2xl p-6 text-sm text-zinc-400">Loading promotions…</section>;
  }

  return (
    <div className="space-y-4">
      <section className="vl-panel rounded-2xl p-5 sm:p-6">
        <h2 className="text-lg font-semibold text-white">Buy X Get Y promotions</h2>
        <p className="mt-2 text-sm text-zinc-400">
          Every promotion here runs on one shared engine: buy X eligible items, get Y of them at a reduced price. The
          discounted items are always the cheapest ones in the cart, counted across the whole order rather than per
          product. At most one of these applies to an order — the one worth the most — and it competes with coupons,
          referral codes, membership pricing and bulk savings under the store&apos;s existing &ldquo;best single
          discount wins&rdquo; rule.
        </p>
        {initialBuy3Get1Enabled ? (
          <p className="mt-3 text-xs text-zinc-500">
            The Control Center&apos;s &ldquo;Enable Buy 3 Get 1 Free&rdquo; checkbox is the same switch as the one on
            that promotion below. Changing either changes both.
          </p>
        ) : null}
      </section>

      {message ? <p className="rounded-lg border border-emerald-300/30 bg-emerald-300/10 px-3 py-2 text-sm text-emerald-200">{message}</p> : null}
      {error ? <p className="rounded-lg border border-red-400/30 bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p> : null}

      {promotions.map((promotion) => (
        <PromotionCard
          key={promotion.id}
          promotion={promotion}
          productSlugs={productSlugs}
          saving={savingId === promotion.id}
          onChange={(patch) => update(promotion.id, patch)}
          onSave={() => save(promotion)}
        />
      ))}
    </div>
  );
}

function PromotionCard({
  promotion,
  productSlugs,
  saving,
  onChange,
  onSave,
}: {
  promotion: PromotionRow;
  productSlugs: string[];
  saving: boolean;
  onChange: (patch: Partial<BxgyPromotion>) => void;
  onSave: () => void;
}) {
  // Recomputed from the form's own values rather than read from the server, so
  // the badge tracks an unsaved schedule change as the admin types it.
  const scheduled = isPromotionScheduled(promotion, new Date());
  const live = promotion.enabled && scheduled;
  const status = live ? "LIVE" : promotion.enabled ? (scheduled ? "LIVE" : "Scheduled") : "Off";

  const preview = useMemo(() => ({
    headline: promotionHeadline(promotion),
    description: storefrontDescription(promotion),
    group: groupSize(promotion),
  }), [promotion]);

  const field = "w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white placeholder:text-zinc-600";
  const label = "block text-xs font-medium uppercase tracking-[0.14em] text-zinc-500";

  return (
    <section className="vl-panel rounded-2xl p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="text-lg font-semibold text-white">{promotion.name}</h3>
            <span
              className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${
                live
                  ? "border-emerald-300/40 bg-emerald-300/10 text-emerald-200"
                  : promotion.enabled
                    ? "border-amber-300/40 bg-amber-300/10 text-amber-200"
                    : "border-white/20 bg-white/5 text-zinc-300"
              }`}
            >
              {status}
            </span>
          </div>
          <p className="mt-2 text-sm text-zinc-400">{preview.description}</p>
          <p className="mt-1 text-xs text-zinc-500">
            Storefront headline: <span className="text-zinc-300">{preview.headline}</span> · one reward group is{" "}
            {preview.group} eligible items.
          </p>
        </div>

        <button
          type="button"
          role="switch"
          aria-checked={promotion.enabled}
          aria-label={`Toggle ${promotion.name}`}
          disabled={saving}
          onClick={() => onChange({ enabled: !promotion.enabled })}
          className={`relative inline-flex h-11 w-[4.75rem] shrink-0 items-center rounded-full border transition disabled:opacity-60 ${
            promotion.enabled ? "border-emerald-300/50 bg-emerald-400/30" : "border-white/20 bg-white/10"
          }`}
        >
          <span
            className={`inline-block h-9 w-9 transform rounded-full bg-white shadow transition ${
              promotion.enabled ? "translate-x-[2.05rem]" : "translate-x-0.5"
            }`}
          />
        </button>
      </div>

      <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <div>
          <label className={label} htmlFor={`${promotion.id}-buy`}>Buy quantity (X)</label>
          <input
            id={`${promotion.id}-buy`} type="number" min={1} max={100} className={`${field} mt-1.5`}
            value={promotion.buyQuantity}
            onChange={(event) => onChange({ buyQuantity: Math.max(1, Number(event.target.value) || 1) })}
          />
        </div>
        <div>
          <label className={label} htmlFor={`${promotion.id}-get`}>Get quantity (Y)</label>
          <input
            id={`${promotion.id}-get`} type="number" min={1} max={100} className={`${field} mt-1.5`}
            value={promotion.getQuantity}
            onChange={(event) => onChange({ getQuantity: Math.max(1, Number(event.target.value) || 1) })}
          />
        </div>
        <div>
          <label className={label} htmlFor={`${promotion.id}-reward`}>Reward (% off each)</label>
          <input
            id={`${promotion.id}-reward`} type="number" min={1} max={100} className={`${field} mt-1.5`}
            value={promotion.rewardPercent}
            onChange={(event) => onChange({ rewardPercent: Math.min(100, Math.max(1, Number(event.target.value) || 1)) })}
          />
          <p className="mt-1 text-[11px] text-zinc-500">100 = free.</p>
        </div>

        <div>
          <label className={label} htmlFor={`${promotion.id}-starts`}>Starts</label>
          <input
            id={`${promotion.id}-starts`} type="datetime-local" className={`${field} mt-1.5`}
            value={toLocalInputValue(promotion.startsAt)}
            onChange={(event) => onChange({ startsAt: fromLocalInputValue(event.target.value) })}
          />
          <p className="mt-1 text-[11px] text-zinc-500">Blank starts immediately.</p>
        </div>
        <div>
          <label className={label} htmlFor={`${promotion.id}-ends`}>Ends</label>
          <input
            id={`${promotion.id}-ends`} type="datetime-local" className={`${field} mt-1.5`}
            value={toLocalInputValue(promotion.endsAt)}
            onChange={(event) => onChange({ endsAt: fromLocalInputValue(event.target.value) })}
          />
          <p className="mt-1 text-[11px] text-zinc-500">Blank never expires. Expiry is automatic.</p>
        </div>
        <div>
          <label className={label} htmlFor={`${promotion.id}-max-rewards`}>Max free items per order</label>
          <input
            id={`${promotion.id}-max-rewards`} type="number" min={0} className={`${field} mt-1.5`}
            placeholder="No cap"
            value={limitToText(promotion.maxRewardUnitsPerOrder)}
            onChange={(event) => onChange({ maxRewardUnitsPerOrder: textToLimit(event.target.value) })}
          />
        </div>

        <div>
          <label className={label} htmlFor={`${promotion.id}-max-redemptions`}>Total redemptions</label>
          <input
            id={`${promotion.id}-max-redemptions`} type="number" min={0} className={`${field} mt-1.5`}
            placeholder="Unlimited"
            value={limitToText(promotion.maxRedemptions)}
            onChange={(event) => onChange({ maxRedemptions: textToLimit(event.target.value) })}
          />
          <p className="mt-1 text-[11px] text-zinc-500">Counted from paid orders; a refund or cancellation gives one back.</p>
        </div>
        <div>
          <label className={label} htmlFor={`${promotion.id}-per-customer`}>Per customer</label>
          <input
            id={`${promotion.id}-per-customer`} type="number" min={0} className={`${field} mt-1.5`}
            placeholder="Unlimited"
            value={limitToText(promotion.perCustomerLimit)}
            onChange={(event) => onChange({ perCustomerLimit: textToLimit(event.target.value) })}
          />
        </div>
        <div>
          <label className={label} htmlFor={`${promotion.id}-priority`}>Priority</label>
          <input
            id={`${promotion.id}-priority`} type="number" className={`${field} mt-1.5`}
            value={promotion.priority}
            onChange={(event) => onChange({ priority: Number(event.target.value) || 0 })}
          />
          <p className="mt-1 text-[11px] text-zinc-500">Tie-break only. Value always wins first.</p>
        </div>

        <div className="sm:col-span-2 lg:col-span-3">
          <label className={label} htmlFor={`${promotion.id}-include`}>Eligible products</label>
          <input
            id={`${promotion.id}-include`} className={`${field} mt-1.5`} list={`${promotion.id}-slugs`}
            placeholder="Blank = every product. Otherwise comma-separated slugs."
            value={slugsToText(promotion.eligibility.includeSlugs)}
            onChange={(event) => onChange({
              eligibility: { ...promotion.eligibility, includeSlugs: textToSlugs(event.target.value) },
            })}
          />
        </div>
        <div className="sm:col-span-2 lg:col-span-3">
          <label className={label} htmlFor={`${promotion.id}-exclude`}>Excluded products</label>
          <input
            id={`${promotion.id}-exclude`} className={`${field} mt-1.5`} list={`${promotion.id}-slugs`}
            placeholder="Comma-separated slugs. Exclusions always win."
            value={slugsToText(promotion.eligibility.excludeSlugs)}
            onChange={(event) => onChange({
              eligibility: { ...promotion.eligibility, excludeSlugs: textToSlugs(event.target.value) },
            })}
          />
          <datalist id={`${promotion.id}-slugs`}>
            {productSlugs.map((slug) => <option key={slug} value={slug} />)}
          </datalist>
        </div>
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-4">
        <label className="flex items-center gap-2 text-sm text-zinc-300">
          <input
            type="checkbox" checked={promotion.stackWithCoupon}
            onChange={(event) => onChange({ stackWithCoupon: event.target.checked })}
          />
          Allow a coupon code on top
        </label>
        <label className="flex items-center gap-2 text-sm text-zinc-300">
          <input
            type="checkbox" checked={promotion.stackWithBundlePricing}
            onChange={(event) => onChange({ stackWithBundlePricing: event.target.checked })}
          />
          Combine with Bundle &amp; Save pricing
        </label>
      </div>
      <p className="mt-2 text-xs text-zinc-500">
        With coupon stacking off, a coupon competes with this promotion and the larger discount wins. With bundle
        pricing off, a free item is valued at full price and competes with the quantity discount instead of adding to
        it.
      </p>

      <div className="mt-5 flex items-center gap-3">
        <button
          type="button"
          onClick={onSave}
          disabled={saving}
          className="rounded-lg border border-emerald-300/40 bg-emerald-400/20 px-4 py-2 text-sm font-semibold text-emerald-100 transition hover:bg-emerald-400/30 disabled:opacity-60"
        >
          {saving ? "Saving…" : "Save promotion"}
        </button>
        {promotion.enabled && !scheduled ? (
          <span className="text-xs text-amber-200">
            Switched on but outside its schedule — it will activate and expire on its own.
          </span>
        ) : null}
      </div>
    </section>
  );
}
